[package]
name = "schema"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.0.0", default-features = false }
diesel-derive-enum = { version = "2.0.0-rc.0", features = ["postgres"], default-features = false }
